package today.sesac.versebyverse.ai.prompt;

/**
 * AI 프롬프트 기능을 구분하는 열거형입니다.
 */
public enum PromptType {

    // 게시글 관련 프롬프트 타입
    POST_HIPSTER_FEED,
    POST_COMMENTARY,
    POST_MIDNIGHT_RADIO,
    POST_COLUMN,
    POST_CONTRIBUTION,
    POST_BOOK_REVIEW,
    POST_MODERN_LITERATURE,
    POST_CLASSICAL_LITERATURE,
    POST_ESSAY,

    // 댓글 관련 프롬프트 타입
    COMMENT_HIPSTER_FEED,
    COMMENT_COMMENTARY,
    COMMENT_MIDNIGHT_RADIO,
    COMMENT_COLUMN,
    COMMENT_CONTRIBUTION,
    COMMENT_BOOK_REVIEW,
    COMMENT_MODERN_LITERATURE,
    COMMENT_CLASSICAL_LITERATURE,
    COMMENT_ESSAY

}