version: '3'
services:
  mysql:
    container_name: versebyverse-mysql
    image: mysql:8.4
    # 한글 사용 위해 utf8mb4 설정
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql # [호스트의 ./mysql-data 폴더] ←→ [컨테이너의 /var/lib/mysql 폴더](MySQL 데이터베이스의 실제 저장 경로)(이 폴더를 호스트에도 연결해두면, 컨테이너를 삭제해도 DB 내용이 지워지지 않음)
      - ./mysql-conf/my.cnf:/etc/mysql/conf.d/my.cnf  # 설정 마운트
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: UTC # 타임존 설정
  mysql-test:
    container_name: versebyverse-mysql-test
    image: mysql:8.4
    # 한글 사용 위해 utf8mb4 설정
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    ports:
      - '${DB_TEST_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_TEST_NAME}
      MYSQL_USER: ${DB_TEST_USERNAME}
      MYSQL_PASSWORD: ${DB_TEST_PASSWORD}
      TZ: UTC # 타임존 설정