spring:
  application:
    name: shoutify


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 이미 설치되어 있을 수 있어서 포트 번호를 임의로 변경
    url: jdbc:mysql://localhost:${DB_PORT:3306}/${DB_NAME:shoutify}?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: create # DDL 자동 생성 설정, entity 클래스에 따라 테이블을 생성함.
    properties:
      hibernate:
        format_sql: true # 콘솔 창에서 SQL을 보기 좋게 출력함.(줄바꿈, 들여쓰기 등)
        show-sql: true # hibernate가 실행하는 SQL을 로그로 출력

  web:
    resources:
      add-mappings: false

  #vertex ai
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${AI_PROJECT_ID}
          location: us-central1
          credentials-uri: classpath:${AI_KEY_JSON}
          chat:
            options:
              model: gemini-2.0-flash
              temperature: 0.5

# log level 설정, 예: trace, debug, info, warn, error
logging:
  level:
    root: INFO
    org.springframework.ai: DEBUG
    com.google.cloud.aiplatform.v1: DEBUG
    io.grpc: DEBUG
    org:
      springframework: info # slf4j 로그 레벨 설정
      hibernate.SQL: DEBUG # hibernate가 실행하는 SQL을 로그로 출력
